#
# Copyright 2022-2024 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
version=2.0.0-build.9999

org.gradle.workers.max=3
org.gradle.parallel=true
org.gradle.caching=true

baseGemFireVersion=10.2
baseSpringVersion=4.1

springTestGemfireDockerImage=tds-gemfire-docker-dev-local.usw1.packages.broadcom.com/pivotal-gemfire/vmware-gemfire:blessed-10.2-jdk17
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8

additionalMavenRepoURLs=

