#
# Copyright 2022-2024 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
springDataGemFireVersion=1.0.4
version=1.0.4-build.9999
gemfireVersion=10.1.3

mavenPushRepository=
org.gradle.workers.max=3
org.gradle.parallel=true

springTestGemfireDockerImage=gemfire/gemfire:10.1-jdk17
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8

additionalMavenRepoURLs=

