/*
 * Copyright 2024-2026 Broadcom. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

plugins {
  id 'groovy-gradle-plugin'
}

repositories {
  def repositoryConfigFilePath = providers.gradleProperty("spring.gemfire.repositories").getOrElse(
    providers.environmentVariable("HOME").get() + "/.gradle/gradleRepositories.json"
  )

  def jsonString = new File(repositoryConfigFilePath).getText("UTF-8")
  def repoConfig = new groovy.json.JsonSlurper().parseText(jsonString)
  ((List) repoConfig["repositories"]).findAll { it != null }.each { entry ->
    maven {
      url = uri(entry["url"] as String)
      if (entry["username"]?.toString()?.trim()) {
        credentials {
          username = entry["username"] as String
          password = entry["password"] as String
        }
      }
    }
  }

  if (providers.gradleProperty("useMavenCentral").getOrElse("false").toBoolean()) {
    mavenCentral()
  }
}

dependencies {
  implementation(gradleApi())

  testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

tasks.withType(Test).configureEach {
  useJUnitPlatform()
}

group = 'org.apache.geode.gradle'
version = 1.0

gradlePlugin {
  plugins.register('gemfire-server-integration-test-plugin') {
    id = 'gemfire-server'
    implementationClass = 'build.GemFireServerPlugin'
  }
}
