[versions]
assertjVersion = "3.23.1"
awaitilityVersion = "4.2.2"
benManesVersions = "0.50.0"
gemFireTestContainersVersion = "2.3.3"
jakartaAnnotationApiVersion = "2.1.1"
jakartaServletApiVersion = "6.0.0"
jsr305Version = "3.0.2"
junitVersion = "4.13.2"
littlerobotsVersionCatalogUpdate = "0.8.5"
logbackVersion = "1.5.12"
lombokVersion = "8.6"
mockitoVersion = "5.14.2"
multithreadedtcVersion = "1.01"
nebulaFacetVersion = "11.0.0"
slf4jVersion = "2.0.16"
springSecurityVersion = "6.5.6"
springSessionVersion = "3.5.3"
springShellVersion = "1.2.0.RELEASE"
springVersion = "6.2.12"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertjVersion" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitilityVersion" }
findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305Version" }
gemfire-core = { module = "com.vmware.gemfire:gemfire-core", version.ref = "gemfireVersion" }
gemfire-cq = { module = "com.vmware.gemfire:gemfire-cq", version.ref = "gemfireVersion" }
gemfire-deployment-chained-classloader = { module = "com.vmware.gemfire:gemfire-deployment-chained-classloader", version.ref = "gemfireVersion" }
gemfire-gfsh = { module = "com.vmware.gemfire:gemfire-gfsh", version.ref = "gemfireVersion" }
gemfire-logging = { module = "com.vmware.gemfire:gemfire-logging", version.ref = "gemfireVersion" }
gemfire-tcp-messenger = { module = "com.vmware.gemfire:gemfire-tcp-messenger", version.ref = "gemfireVersion" }
gemfire-tcp-server = { module = "com.vmware.gemfire:gemfire-tcp-server", version.ref = "gemfireVersion" }
gemfire-testcontainers = { module = "dev.gemfire:gemfire-testcontainers", version.ref = "gemFireTestContainersVersion" }
gemfire-version = { module = "com.vmware.gemfire:gemfire-version", version.ref = "gemfireVersion" }
gemfire-wan = { module = "com.vmware.gemfire:gemfire-wan", version.ref = "gemfireVersion" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakartaAnnotationApiVersion" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakartaServletApiVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
log4j-over-slf4j = { module = "org.slf4j:log4j-over-slf4j", version.ref = "slf4jVersion" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoVersion" }
multithreadedtc = { module = "edu.umd.cs.mtc:multithreadedtc", version.ref = "multithreadedtcVersion" }
spring-data-gemfire = { module = "com.vmware.gemfire:spring-data-3.5-gemfire-10.1", version.ref = "springDataGemFireVersion" }
spring-data-gemfire-test-framework = { module = "com.vmware.gemfire:spring-data-3.5-gemfire-test-framework-10.1", version.ref = "springDataGemFireVersion" }
spring-framework-bom = { module = "org.springframework:spring-framework-bom", version.ref = "springVersion" }
spring-security-bom = { module = "org.springframework.security:spring-security-bom", version.ref = "springSecurityVersion" }
spring-session-core = { module = "org.springframework.session:spring-session-core", version.ref = "springSessionVersion" }
spring-shell = { module = "org.springframework.shell:spring-shell", version.ref = "springShellVersion" }
spring-tx = { module = "org.springframework:spring-tx", version.ref = "springVersion" }

[bundles]
gemfire-dependencies = [
    "gemfire-core",
    "gemfire-cq",
    "gemfire-deployment-chained-classloader",
    "gemfire-gfsh",
    "gemfire-logging",
    "gemfire-tcp-messenger",
    "gemfire-tcp-server",
    "gemfire-version",
    "gemfire-wan",
]

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" }
littlerobots-version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "littlerobotsVersionCatalogUpdate" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokVersion" }
nebula-facet = { id = "com.netflix.nebula.facet", version.ref = "nebulaFacetVersion" }
nebula-facet-integration = { id = "com.netflix.nebula.integtest-standalone", version.ref = "nebulaFacetVersion" }
